
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aadnkvzoikvfcrirhasr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZG5rdnpvaWt2ZmNyaXJoYXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTU3MTIsImV4cCI6MjA1ODc5MTcxMn0.Tn1vMQxSzeK2VOcT3_34cRdlxqR5QaPsQ4UEJCzyWsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use type assertion to make TypeScript recognize our database schema
// This is a workaround since we cannot modify the types.ts file directly
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY) as unknown as ReturnType<typeof createClient<Database>>;
